package com.plectix.simulator;
/**
 * Build constants.
 *
 * !!!! DO NOT EDIT THIS FILE, EDIT TPL FILE INSTEAD !!!!
*/
public final class BuildConstants {
	public static final String BUILD_DATE = "N/A";
	public static final String BUILD_SVN_REVISION = "N/A";
	public static final String BUILD_OS_NAME = "N/A";
	public static final String JAVA_VERSION = "N/A";
	public static final String ANT_JAVA_VERSION = "N/A";
}

