package com.plectix.simulator;
/**
 * Build constants.
 *
 * !!!! DO NOT EDIT THIS FILE, EDIT TPL FILE INSTEAD !!!!
*/
public final class BuildConstants {
	public static final String BUILD_SVN_REVISION = "@build.svn.revision@";
	public static final String BUILD_DATE = "@build.date@";
	public static final String BUILD_OS_NAME = "@build.os.name@";
	public static final String ANT_JAVA_VERSION = "@ant.java.version@";
}

