package com.plectix.simulator;
/**
 * Build constants.
 *
 * !!!! DO NOT EDIT THIS FILE, EDIT TPL FILE INSTEAD !!!!
*/
public final class BuildConstants {
	public static final String BUILD_DATE = "2009-03-16 15:46:08 EDT";
	public static final String BUILD_SVN_REVISION = "7371";
	public static final String BUILD_OS_NAME = "Mac OS X";
	public static final String JAVA_VERSION = "1.5.0_16";
	public static final String ANT_JAVA_VERSION = "1.5";
}

